module.exports = {
    name: 'Liliput',
    route: '/',
    routeHistory: [],
    location: {
      lat : -45.87454839999999,
      lng : 170.5038241
    },
    markers: [],
    liliputs: [
      '17 John St	Abbotsford',
      '1 Precelly Street	Allanton',
      '9 Sunbury St	Andersons Bay',
      '21 Hunt St	Andersons Bay',
      '217 Somerville St	Andersons Bay',
      '218 Musselburgh Rise	Andersons Bay',
      '44 Merchiston Street	Andersons Bay',
      '1 Muri Street	Aramoana',
      '51 Bayfield Road	Bayfield',
      '32 Rosebery St	Belleknowes',
      '1020 Brighton Road	Brighton',
      '2 Scroggs Hill Rd	Brighton',
      '68 Greig Street	Broad Bay',
      '61 Caldwell St	Brockville',
      '51 Waimea Ave	Calton Hill',
      'College of Ed Auditorium	Campus',
      'Marsh Study Centre	Campus',
      '30 Harbour Tce	Careys Bay',
      '51A Thorn St	Caversham',
      '373 Rattray Street	City',
      '45 Sutherland St	City',
      '7 Montpellier St	City',
      '29 Lees St	Dunedin Central',
      'Queen Mary	Dunedin Hospital',
      '35 Flower St	Fairfield',
      '18a Brighton Road	Green Island',
      '21 Edinburgh Street	Green Island',
      '3C Church St	Green Island',
      '457 Taieri Rd	Halfway Bush',
      '18 Tidewater Drive	Harrington Point',
      '95 Centennial Ave	Helensburgh',
      '7 Kakanui Road	Kakanui',
      '4 Pennant St	Kaikorai',
      '61 County Rd	Kaikorai',
      '8 Hillary Street	Liberton',
      '13 Wharfdale St	Macandrew Bay',
      '7 Bayne Terrace	Macandrew Bay',
      'opp Bellamys Gallery	Macandrew Bay',
      '5 Jessie St	Maia',
      '71 Newington Ave	Maori Hill',
      '93 Mornington Road	Mornington',
      '1 Kinmont Cres	Mosgiel',
      '11 Brookside Place	Mosgiel',
      '167 Wingatui Road	Mosgiel',
      'Spruce	Mosgiel',
      '22 Montague St	NEV',
      'NEV Primary School	NEV',
      '47 Oregon St	Ocean Grove',
      '14 Signal Hill Rd	Opoho',
      '82 Signal Hill Rd	Opoho',
      '19 Hoylake St	Outram',
      '7 Scotia Street	Port Chalmers',
      'Port Chalmers School	Port Chalmers',
      '45 Seaton Road	Portobello',
      '12 Monowai Road	Ravensbourne',
      '251 Ravensbourne Rd	Ravensbourne',
      '1 Avon St	Roslyn',
      '11 Selkirk St	Roslyn',
      'Sawyers Bay School	Sawyers Bay',
      '469 Hillside Rd	South Dunedin',
      '116 Norfolk St	St Clair',
      '34 Allandale Road	St Clair',
      '15 A Marlow St	St Kilda',
      '32 Hargest Cres	St Kilda',
      'St Leonards School	St Leonards',
      '17 Cashel Street	Sth Dunedin',
      '243 Oxford Street	Sth Dunedin',
      '19 Magdala St	Tainui',
      '23 Stewart St	Waikouaiti',
      '28 Brown Street	Waitati',
      '31 Craighall Cres	Wakari',
      '21 Delta Drive	Waldronville',
      '381 Brighton Rd	Waldronville',
      '3 Perry St	Warrington',
      '137 Doone St	Waverley',
      '40 Scobie Road	Waverley'
    ]
}
